# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- pr

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: $(solution)
    feedsToUse: 'config'
    nugetConfigPath: './nuget.config'
    noCache: true

# - task: SonarCloudPrepare@1
#   inputs:
#     SonarCloud: 'SonarCloud'
#     organization: 'devteam-nebraskabook-org'
#     scannerMode: 'MSBuild'
#     projectKey: 'NebraskaBook_MMSProject'
#     projectName: 'MMS'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: $(solution)
    arguments: '-v minimal -c $(buildConfiguration) --no-restore'

# Run Code Analysis task
# - task: SonarCloudAnalyze@1

# # Publish Quality Gate Result task
# - task: SonarCloudPublish@1
#   inputs:
#     pollingTimeoutSec: '300'

# - task: sonarcloud-buildbreaker@2
#   inputs:
#     SonarCloud: 'SonarCloud'
#     organization: 'devteam-nebraskabook-org'
